### PR TITLE
Move Theme Demos into master

### PR DESCRIPTION
**Pull request by joebochill**
Changes proposed in this Pull Request:
- Move the approved demos into the master branch
- Add demo links in the README files
- Add missing dependency to the react demo

### CODE REVIEW

**Comment by joebochill** [comment]
Is this an issue in the demo implementation or just a difference between the two themes default card colors? I know angular stepper has a lot of issues being customized. 

If it’s an issue with the theme itself, we should log it as a theme bug.

**Comment by jeffvg** [comment]
was going to change background color on cards to be #1d2529 or close to the react cards

**Comment by joebochill** [comment]
If both demos are using the default card styles and they look different, that’s a bug on the themes themselves, not an issue with the demo. We don’t want to be doing any one-off styling in the demo to make them look the same between frameworks. The whole point of doing the demos is to identify discrepancies with the themes, so we don’t want to hide them. We want to go through and catalog all the differences we se between the two examples and then log bugs for them so we can fix them in the themes package itself.

**Comment by emclaug2** [comment]
I'm going to open up issues for all the angular demo's theme inconsistencies.  I know there were some css overrides used in a few places to coverup the differences.  Once these issues are addressed, the card styles will match.   We should be good to merge this in.

**Pull request merged**
