### PR TITLE
[NG-#1A]Release Angular Themes 6.0.1

### PR DESCRIPTION
**Pull request by daileytj**
Fix build to release Angular Themes 6.0.1

### CODE REVIEW

**Review by joebochill — APPROVED** [review]

**Comment by huayunh** [comment]
image
Color of an active item should be blue500 in dark theme, and blue200 in light theme

**Comment by huayunh** [comment]
And why do we need to publish a 6.0.1? I noticed that in NPM we don't have a 6.0.0 published yet.

**Comment by joebochill** [comment]
> And why do we need to publish a 6.0.1? I noticed that in NPM we don't have a 6.0.0 published yet.

6.0.0 was unpublished because it was catastrophically broken without the mixins folder. NPM won't let you publish over a previously published version.

**Comment by jeffvg** [comment]
should angular demo have toggle for both themes?

**Comment by emclaug2** [comment]
@jeffvg Are you referring to this? 

image

This icon should never disappear.

**Comment by jeffvg** [comment]
> @jeffvg Are you referring to this?
> 
> image
> 
> This icon should never disappear.

it's there....
image

**Comment by jeffvg** [comment]
getting fresh clone

**Review by emclaug2 — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
