### PR TITLE
Use black500 for the shadow color

### PR DESCRIPTION
**Pull request by huayunh**
partially address #90 

#### Changes proposed in this Pull Request:
- Use black500 for the shadow color instead of pure black to match design

#### Screenshots:
image

#### TODO
Make this more elegant

### CODE REVIEW

**Comment by joebochill** [comment]
This looks like it will work for now, but we are making some assumptions that may reduce the futureproof-ness of this (length of the array, color being used, string formatting).

Also, going from pure black to black[500] is a quite lighter color...how does that affect the appearance of some of the default shadows?

**Comment by joebochill** [comment]
Are we working on this? Do we need to keep this open?

**Comment by huayunh** [comment]
> Also, going from pure black to black[500] is a quite lighter color...how does that affect the appearance of some of the default shadows?

image

**Comment by joebochill** [comment]
The color looks okay to me. Are we still working on cleaning up the elegance? If we're not actively working on it, I'd rather close the PR and come back to it when we are. Otherwise it's just clogging up the review pipeline.

**Comment by huayunh** [comment]
I have some trouble merging dev into this branch...

**Review by joebochill — APPROVED** [review]

**Pull request merged**
