### PR TITLE
Updates to react themes (mostly dark, but also some light changes)

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX

#### Changes proposed in this Pull Request:
- Updates to React light and dark theme to match the designs from Figma
- Made some variables for frequently re-used colors so we don't have to constantly use colors directly from the colors package (should make it easier to change things if we need to in the future)
- Dumped a bunch of components into the theme demo

> *NOTE*: I checked in the nasty updates to the theme demo to make testing easier, but we can back those out before merging into dev if we want...or we can leave it as a starting point for the Kitchen Sink update that we've been meaning to do.

#### Screenshots:
image
image

### CODE REVIEW

**Comment by huayunh** [comment]
Would you want to commit your showcase somewhere so that it is easier for us to review the component styles?

**Comment by joebochill** [comment]
> Would you want to commit your showcase somewhere so that it is easier for us to review the component styles?

I used the theme demo, not the showcase:
```
cd themes
yarn start:react
```

**Comment by emclaug2** [comment]
I'm taking a look at this now. 👍

**Comment by emclaug2** [comment]
This is the snackbar for the light theme: 

image


Should the ACTION 'X" be defaulted to blue[200]?

**Comment by emclaug2** [comment]
Here's dark-theme snackbar: 

image

"Undo" should be blue[500].

**Comment by emclaug2** [comment]
@joebochill 

Is there an example of a bottomsheet anywhere in this theme demo ?

**Comment by emclaug2** [comment]
This border color looks a little dark to me; can I get second set of eyes on this?

image

**Comment by huayunh** [comment]
image
These guys shall use the 500 colors

**Comment by huayunh** [comment]
Divider, hint text, disabled text should use alpha level 0.36, not 0.32

**Comment by huayunh** [comment]
image
not implemented

**Comment by huayunh** [comment]
An icon inside a chip should be 18x18
image

(The size of an avatar is 24x24, the way you are implementing right now)

**Comment by huayunh** [comment]
If using avatars in chips is desirable, here's what I would recommend for the colors:
image

**Comment by huayunh** [comment]
You shouldn't need to do `.rgb()` before `.string()`

image

**Comment by huayunh** [comment]
For button groups
image

Unlike toggle buttons, I don't see them used anywhere in our projects, and they are not explicitly encouraged by Material Design either. The style here is just Material buttons' dark style stitched together.

**Comment by huayunh** [comment]
Was it impossible to change the outline colors? 
image

**Comment by huayunh** [comment]
image
Placeholder text color should be black300 36%

**Comment by huayunh** [comment]
This hover color is too glaring 
image

**Comment by huayunh** [comment]
MuiFormLabel-filled should be textPrimary for better readability

image

**Comment by huayunh** [comment]
For the disabled filled button, change the button text to black400
(L: Figma; R: screenshot from demo)
image

**Comment by huayunh** [comment]
(Screenshot from demo:)
image
border color should be blue200

**Comment by huayunh** [comment]
Use the opacity to make filled variant text field look more disabled

(L:Figma)
image

**Comment by huayunh** [comment]
In tabs, the font weight actually changes to "regular"(400) for the inactive items, while the active ones stay semibold (600)

image

**Review by huayunh — CHANGES_REQUESTED** [review]
I like what you are doing to those secondary buttons. That's actually close to another proposed design Kyle made, except that it is not used anywhere in any current projects.

And, since this is a breaking change on the theme, are we going to do it in another PR to change the subtitle1 to font-weight 600, before we publish version 6.0.0?

**Comment by huayunh** [comment]
light theme:
hover color of an active toggle button... should probably change to blue100
image

**Comment by huayunh** [comment]
outlined 
image

disabled and regular text field's border should both be the divider color (black500 12%)

**Comment by huayunh** [comment]
Inactive error item (error but not focused) border width should be 1px all the time

Only active error items (error and focused) would have 2px border

**Comment by huayunh** [comment]
again, let's use textPrimary for the filled text label

image

**Comment by emclaug2** [comment]
> Was it impossible to change the outline colors?
> 
> (From figma:)
> image

Should the outline be red[500] when focused?

**Comment by huayunh** [comment]
I'm thinking this:
* inactive: red500, 1px
* hover: red200, 1px
* focused: red500, 2px

I know it might be strange, I just wanted some indication that the mouse is hovering on the text field.
But if we are not happy with this, we may keep the hover state to be red500

**Comment by joebochill** [comment]
> This is the snackbar for the light theme:
> Should the ACTION 'undo' be defaulted to blue[200]?

Where are you testing this? My demo is using the correct colors for the snackbar:
image

**Comment by joebochill** [comment]
> image
> not implemented

???

image


image

**Comment by joebochill** [comment]
> An icon inside a chip should be 18x18 (From Figma):
> (The size of an avatar is 24x24, the way you are implementing right now)

Icons and avatars are passed in as JSX.Elements....the end user is responsible for setting their size when passing them in.

**Comment by joebochill** [comment]
> If using avatars in chips is desirable, here's what I would recommend for the colors:
> image

Avatars are passed in as JSX.Elements. The end user is responsible for setting it's size and color when passing it it...what you see in the demo is the default colors for the avatar component.

**Comment by joebochill** [comment]
> > If using avatars in chips is desirable, here's what I would recommend for the colors:
> > image
> 
> Avatars are passed in as JSX.Elements. The end user is responsible for setting it's size and color when passing it it...what you see in the demo is the default colors for the avatar component.
> 
> I would prefer to avoid cross-component overrides (e.g., styles for an icon in a button, or an avatar in a chip) because they require hardcoding the class name (you can't programmatically reference the classes from another component override object), making them very brittle and prone to breaking if MUI ever changes the names. And it makes it more difficult for end-users to override them via the typical methods provided by MUI (e.g., `<MyIcon fontSize={'small'} />`) may no longer work if our rule is more specific.

**Comment by joebochill** [comment]
> Was it impossible to change the outline colors?
> 
> (From figma:)
> image

This is implemented. Which part are you not seeing?

**Comment by joebochill** [comment]
> I'm thinking this:
> 
> * inactive: red500, 1px
> * hover: red200, 1px
> * focused: red500, 2px
> 
> I know it might be strange going back and forth between 200 and 500 colors — I just wanted some indication that the mouse is hovering on the text field.
> But if we are not happy with this, we may keep the hover state to be red500

This is exactly how it is implemented right now.

**Comment by emclaug2** [comment]
> > This is the snackbar for the light theme:
> > Should the ACTION 'undo' be defaulted to blue[200]?
> 
> Where are you testing this? My demo is using the correct colors for the snackbar:
> image

If you go to the devices page, scroll all the way to the bottom, select a few items and hit the 'Delete' button.

http://localhost:3000/devices

**Comment by joebochill** [comment]
> This hover color is too glaring
> image

What color would you like?

**Comment by joebochill** [comment]
> Placeholder text color should be black300 36%

Just for filled inputs or all inputs?

**Comment by joebochill** [comment]
> MuiFormLabel-filled should be textPrimary for better readability
> 
> image

This is not a picture of a filled input.

**Comment by joebochill** [comment]
> > MuiFormLabel-filled should be textPrimary for better readability
> > image
> 
> This is not a picture of a filled input. Did you mean to change this for a default/underlined input, or did you use the wrong picture? Or did you want the change for both.

**Comment by joebochill** [comment]
> And, since this is a breaking change on the theme, are we going to do it in another PR to change the subtitle1 to font-weight 600, before we publish version 6.0.0?

I will add this change, we will need to update the DSM

**Comment by joebochill** [comment]
> light theme:
> hover color of an active toggle button... should probably change to blue100
> image

Would you rather match what we are doing for the primary outlined button (blue 500 4% opacity)?

**Comment by huayunh** [comment]
> Would you rather match what we are doing for the primary outlined button (blue 500 4% opacity)?

That would work too. Just not gray.

**Comment by joebochill** [comment]
> If you go to the devices page, scroll all the way to the bottom, select a few items and hit the 'Delete' button.
> Where is the snackbar in your picture located?
> 
> http://localhost:3000/devices

Ah, I see. That one has the button set to `color={'secondary'}`, where mine (in App.js) is using primary. I'll add a rule to cover secondary colors too.

**Comment by joebochill** [comment]
Okay, I think I covered all of the comments above if you want to take another gander.

**Comment by huayunh** [comment]
Can you verify if this is fixed? https://github.com/pxblue/themes/issues/122

**Comment by joebochill** [comment]
> Can you verify if this is fixed? #122

I can confirm that it is not fixed (only for the outlined inputs), but I can make a fix for it pretty quickly.

**Comment by joebochill** [comment]
Fixes #122

**Comment by huayunh** [comment]
## Chips
- [ ] Delete icon size should be 18x18
- [ ] Left icon/leading icon color should be textPrimary by default, not `#616161` or `#e0e0e0`
- [ ] Left icon/leading icon left margin should be 8px not 5px
- [ ] Spacing between leading icon/avatar and the chip label text, and between the chip label text and the delete icon, should be 8px

## Bottom Navigation
- [ ] inactive text should be textSecondary in dark theme

## Button
- [ ] The hover color of the toggle button is still wrong
- [ ] For the default button style, Evan's PR inspired me a bit and I have a different proposal for the default light-themed button. See his PR and Figma for details

## Text Field
- [ ] Label color: initial inactive should use textSecondary (you have textPrimary); blurred should use textPrimary (you have it right). This applies to both dark and light theme
- [ ] For both light and dark theme, the disabled dividers should remain the same (still using theme.palette.divider)
- [ ] Dark theme Fix text field border-color
- [ ] I tried toggling your commented out code to check the icon but it appears to not do anything so I skipped it
- [ ] Default text field hover border styled wrong, should be 1px black200, not `2px solid #e8eaea`

**Comment by huayunh** [comment]
From Evan's PR
image

**Comment by huayunh** [comment]
I don't see the MUI stepper in this kitchen sink. May want to include that for the check

**Comment by joebochill** [comment]
> I don't see the MUI stepper in this kitchen sink. May want to include that for the check

If you go to the 'devices' route, scroll down the page and click the reports tab, there is a stepper:
image

**Comment by huayunh** [comment]
Stepper looks good

**Comment by joebochill** [comment]
> ## Bottom Navigation
> * [ ]  inactive text should be textSecondary in dark theme

image
image
image

what am i missing?

**Comment by huayunh** [comment]
i must be drunk, I meant to say textPrimary

**Comment by joebochill** [comment]
> ## Text Field
> * [ ]  Label color: initial inactive should use textSecondary (you have textPrimary); blurred should use textPrimary (you have it right). This applies to both dark and light theme

The label is the same component for inactive and active...it just moves and scales. There is no way for me to programmatically determine if the field has text in it from the theme to make it secondary when there is no value entered.

**Comment by joebochill** [comment]
> ## Text Field
> * [ ]  For both light and dark theme, the disabled dividers should remain the same (still using theme.palette.divider)

What is a text field divider?

**Comment by joebochill** [comment]
> ## Text Field
> * [ ]  Default text field hover border styled wrong, should be 1px black200, not `2px solid #e8eaea`

Are you talking about the underline? The outlined variant is the only one with a border. If you're talking about the underline, making it 1px introduces inconsistencies with the error version which uses 2px. And if you tell me to make the error 1px to match, then the error no longer has any hover state changes from inactive.

**Comment by joebochill** [comment]
I added a button above the text inputs that you can click to toggle on/off the icons in the text fields.

**Comment by joebochill** [comment]
> From Evan's PR
> image

This is addressed in https://github.com/pxblue/react-component-library/pull/245

**Comment by huayunh** [comment]
- [ ] In the light theme, have `<Fab />` default style follows that of the default contained-styled button
- [ ] Light theme disabled text should be `rgba(66, 78, 84, 0.3)`. Right now you can barely tell the difference between enabled and disabled underlined text fields.
- [ ] Mobile stepper dots should have an 8px spacing between them
- [ ] In chips, between an Avatar and the label text, the spacing should be 8px too
- [ ] In chips when there is only text, both the left padding and the right padding should be 12px instead of 8px
- [ ] In secondary chips, the leading icon's left margin should be 8px too. Match primary.
- [ ] I turned on the text field icon toggle. And I am sure you are not going to like it. The positioning of the icons and labels are all... off. I suggest making another story to polish the "complex text fields", in the spirit that we can still call this a sprint, not a marathon. I uploaded my suggested styles into Figma.
  - [ ] But for this round, the leading and trailing icons in the dark theme disabled text field should be the disabled text color. I think those are fairly common in our projects.
- [ ] black100 for light theme text field placeholder text
- [ ] if I add `value={234}` to a textField, the label would have the wrong color. Should be their respective disabled color in both light theme and dark theme.

**Comment by joebochill** [comment]
> * [ ]  I turned on the text field icon toggle. And I am sure you are not going to like it. The positioning of the icons and labels are all... off. I suggest making another story to polish the "complex text fields", in the spirit that we can still call this a sprint, not a marathon. I uploaded my suggested styles into Figma.
>   
>   * [ ]  But for this round, the leading and trailing icons in the dark theme disabled text field should be the disabled text color. I think those are fairly common in our projects.

I did a little bit of a hack (yay negative margins) to make sure that the icon (whether it is in an iconButton or standalone) aligns to the 12px padding. What you have in your Figma design with the label next to the start adornment is going to be much more of a challenge (because a user can pass in any element they want to the startAdornment - icons and iconButtons are going to be the most common).

The IconButtons being passed in do not inherit the disabled status of the input field in which they are placed...notice you can actually still interact with them. In this case, the end user just needs to add the disabled prop to the IconButton used as the adornment and the correct colors will be used.

**Comment by huayunh** [comment]
Almost there! _Pat on the shoulder_

# 0
I didn't realize that the start/end adornment in text fields works that way. That is great news! I think the negative margin thing is already covered by adding an `edge={'start'}`, so there should be no need to manipulate that in the theme.

The problem now is the start position
image
is a bit off... but we can tolerate that for a while. If you are going to write a story about polishing the text field, make sure to include this point.

# 1
These three labels boxed in purple should all be red200
image

The first two should be blue200, the final one is correct
image

The same applies to all three variants... and the light theme

# 2
image
The outline of the outlined variant in secondary color is blue200 (or is that lightBlue200?). Should be lightBlue200. Same applies to the default secondary one. The filled one looks correct to me.

# 3
Default Buttons - Flat - hovered, the color should be black400, not black300

**Comment by joebochill** [comment]
> The outline of the outlined variant in secondary color is blue200 (or is that lightBlue200?). Should be lightBlue200. Same applies to the default secondary one. The filled one looks correct to me.

I'm assuming you mean it should be lightBlue[_500_]? It's already lightBlue[200]. The filled one is actually using blue[500] for the underline of secondary, so I switched that to lightBlue[500] too.

**Comment by joebochill** [comment]
For the sake of not leaving this PR open...if you find anything else, I would suggest capturing them as a bug and I will fix them quickly on monday.

**Review by huayunh — COMMENTED** [review]
In honor of you making those edits before the camping trip, I will merge this right now. @jeffvg said he will make a spike for the text field thing for you.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
