### PR TITLE
React theme cleanup items

### LINKED ISSUE #138: React theme enhancement
# Button 
- [ ] Button - dark theme - enabled state - hover, the background color should be the hover color (black50 10%)

# Stepper
- [ ] Currently active step, text in the blue circle should be weight 600. Other steps, visited or unvisited, should be the regular caption font
- [ ] dark theme, visited steps, label text, textSecondary. No changes for the light theme

# Tabs
- [ ] when you add an `icon={<MailIcon />}` to the `<Tab />` and make it an up-down structure, the icon should not have that bottom margin that pushes the label text and icon away from each other

# Text Fields
- [ ] Light theme, helper text in a disabled text field should also have a disabled color.

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-1881
Fixes #138 

#### Changes proposed in this Pull Request:
- Fix the border color issue for disabled text-variant button groups (primary and secondary)

#### Screenshots:
before:
image
after:
image

### CODE REVIEW

**Comment by huayunh** [comment]
Is the stepper also fixed?

**Comment by joebochill** [comment]
> Is the stepper also fixed?

Should be.

image
image

**Comment by huayunh** [comment]
image
For outlined and default text field variants, the "234" thing should be the same disabled color as the other visual elements

And you may want to update the progress bar colors in the dark theme. There is a design for that in Figma.

**Comment by huayunh** [comment]
Otherwise looks awesome

**Comment by joebochill** [comment]
> And you may want to update the progress bar (`<LinearProgress />` and `< CircularProgress />`) colors in the dark theme. There is a design for that in Figma.

Using a transparency on the progress bar causes an issue when using the 'buffer' variant because the animated dots appear behind the rail background:
image

**Comment by huayunh** [comment]
That is too bad... 

Then for the buffered one I'm happy if you just use a color picker for that secondary color

**Comment by joebochill** [comment]
> That is too bad...
> 
> Then for the buffered one I'm happy if you just use a color picker for that secondary color

What do you mean 'use a color picker'?

**Comment by huayunh** [comment]
Like sample the color directly and use that

image

**Comment by joebochill** [comment]
> Like sample the color directly and use that

Not a huge fan of this approach...1) it's a color that is not a part of our color palettes and 2) the sampled color depends on what the background color is.

Can we just use the same background as we are using for the slider rail (black[300])?

**Comment by huayunh** [comment]
Can you provide a screenshot of what that would look like?

**Comment by joebochill** [comment]
> Can you provide a screenshot of what that would look like for buffered one?

Bleh, I just realized the slider is using black[300]...but with an alpha value. So that doesn't actually help us.

**Comment by joebochill** [comment]
@huayunh what if I use the darken function instead of alpha? This is with blue/lightBlue[500].darken(0.7):

image

**Comment by huayunh** [comment]
that is a great idea — I like it! Make sure the dots color are matching too.

**Comment by joebochill** [comment]
> that is a great idea — I like it! Make sure the dots color are matching too.

Which color should they match? Right now the default is using a radial gradient to create the circles and they fade in and out with an animation:
image

**Review by huayunh — APPROVED** [review]
Finally! Only a few small tweaks

## Progress Bar

I wasn't sure where this color in light theme comes from

image

It's only a small tiny little color tweak from the original blue100 in the design (the one on the top)

image

so if I understand where the color comes from, I'm happy to notate that in the design.

## Some secondary colors

For the chips and FAB, I thought we are going to apply the same strategy we had for the buttons?

Instead of 
image
I thought we are doing 
image

**Comment by joebochill** [comment]
> ## Progress Bar
> I wasn't sure where this color in light theme comes from
> It's only a small tiny little color tweak from the original blue100 in the design (the one on the top)
> so if I understand where the color comes from, I'm happy to notate that in the design.

I'm not sure where you are seeing that. Light theme is using blue[100] for the rail background:
image
image

> ## Some secondary colors
> For the chips and FAB, I thought we are going to apply the same strategy we had for the buttons?

Updated. It might be worth noting that the hover behavior is different between buttons and chips...buttons darken on hover and chips lighten. Not sure if that's a concern or not.

**Comment by huayunh** [comment]
An aborted git pull on my end that wasn't given proper attention. You have my double thumbs up on this PR.

>  It might be worth noting that the hover behavior is different between buttons and chips...buttons darken on hover and chips lighten. Not sure if that's a concern or not.

Ideally, everything lines up...

**Comment by joebochill** [comment]
> An aborted git pull on my end that wasn't given proper attention. You have my double thumbs up on this PR.
> 
> > It might be worth noting that the hover behavior is different between buttons and chips...buttons darken on hover and chips lighten. Not sure if that's a concern or not.
> 
> Ideally, everything lines up...

I cleaned these up so everything (fabs, buttons , chips) hover colors are lined up now.

**Pull request merged**
