### PR TITLE
Update chip styles

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Fix the chip styles in light and dark mode with particular emphasis on the disabled states

#### Screenshots:
image

image

### CODE REVIEW

**Comment by huayunh** [comment]
I think @daileytj was trying to remove  dist from GitHub repo

**Comment by daileytj** [comment]
> I think @daileytj was trying to remove dist from GitHub repo

True story. I removed the dist folder from the react-native folder and added dist to the .gitignore in the open themes PR.

**Comment by joebochill** [comment]
That should take care of itself so long as my PR goes in first

**Comment by huayunh** [comment]
Yeah just wondering if we are going to do that to all themes repos

**Comment by joebochill** [comment]
I pulled out the dist folder. Somehow in my merge with dev the showcase pointer for react-native change...that might need to be updated again at some point by the next person who goes in there.

**Review by huayunh — COMMENTED** [review]
Dark theme chips leading and delete icon shall be black300 36%, not black50 10%. Otherwise looks good.

**Comment by joebochill** [comment]
> Dark theme chips leading and delete icon shall be black300 36%, not black50 10%. Otherwise looks good.

I'll update the action disabled color to this, but just FYI that is not the color that's shown int he Dark Theme Study file. It's showing black[400] for some reason 🤷

**Comment by huayunh** [comment]
black400 was for the filled ones?

**Review by huayunh — APPROVED** [review]
It seems that right now there are a lot of inline coded styles (the ones calculated via the `color` package). You mayyyy want to have a separate story/issue to clean those up and use the ones defined by the `ThemeColors` constant (will this impact the performance?)

**Comment by joebochill** [comment]
> It seems that right now there are a lot of inline coded styles (the ones calculated via the `color` package). You mayyyy want to have a separate story/issue to clean those up and use the ones defined by the `ThemeColors` constant (will this impact the performance?)

Yeah. I agree. I started to do it and then there were new ones that got added or changed and I didn’t keep up with it. If you want to log an issue to do an audit and refactor out all of the reused colors, we can do that in a follow up.

**Pull request merged**
