### PR TITLE
Feature/ng dark mode

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Dark theme enhancements 

This is still a WIP but it should be about 80% done.  

I would ignore the code for now and just focus on the UI, the code needs refactored.

https://pxb-angular-theme-demo.web.app
Go to the kitchen sink.

### CODE REVIEW

**Comment by emclaug2** [comment]
This branch was made off of Joe's React dark mode PR; so once that's merged in there will be less files edited.

**Review by huayunh — COMMENTED** [review]
Looks like there are still a lot of stylings need to get covered.

Can we update the drawer shadow to use the appropriate elevation (6dp)? And, for the dark theme, the shadow color should be pure black `#000`, so that there will be no more mysterious glows.

There were a few back-and-forths between me and Joe on the button style yesterday. Basically, the style for secondary and warning buttons should be an analogy of that of the primary buttons, but swap colors with their lightBlue and red counter parts.

**Comment by emclaug2** [comment]
Latest changes pushed out here: https://pxb-angular-theme-demo.web.app/

**Comment by emclaug2** [comment]
I'll update the drawer shadows and make the buttons look like this from Joe's PR: 
image

**Review by huayunh — CHANGES_REQUESTED** [review]
The following comments are based on what I see at the moment from https://pxb-angular-theme-demo.web.app/kitchen-sink 

I am documenting whatever I see that feels off, so not everything is tied to this dark theme update. May want to make extra stories/issues for them.

## General
For the showcase itself
- [ ] Overall application dark theme background color shall be darkBlack800
- [ ] That of the light theme shall be white200
- [ ] Set the app bar to primary variant
- [ ] Give that app bar a 4dp shadow

## Date picker
- [ ] The circled date, representing "today", should have a blue circle instead of black or white
  - [ ] blue500 in light
  - [ ] blue200 in dark
  - [ ] Same for the year selection
- [ ] the calendar icon should be 24x24
- [ ] That icon's color should be the same as a secondary text in the dark theme
- [ ] dark theme, when the text field is filled and blurred, the label color should be text primary
- [ ] all dividers should be black200 36% by default, and an inactive underlined text field should use the divider color 
- [ ] when the text field goes active without error, the color should be the primary theme color. In dark theme, this is blue200

## Mobile Stepper
- [ ] the "currently inactive dot" has the wrong color
  - [ ] light theme, gray 200
  - [ ] dark theme, black300 36% (same as disabled color or hint text color)

## Button Toggle
- [ ] Since there is no "primary" "secondary" "error" for the button toggles, follow the color specified in the Figma
- [ ] Remember to use secondary text color for the inactive ones

## Tabs
- [ ] the light theme tabs are using dark chevrons and 

## Buttons
Comments on the light theme:
- [ ] I actually kinda like how the raised basic button and the stroked basic button look in your implementation, but I dislike the way it is done in flat buttons. May want to involve @joebochill  here to steer away from gray default buttons. This is also available in Figma.
image
- [ ] For a raised button, when the mouse is hovering on the button, the button should change its elevation to 4dp
- [ ] stroked warning button, its outline should be red500
- [ ] stroked disabled button, its outline should not be darker than that of an enabled button

## Snack bar
- [ ] light theme text color wrong. Content text should be black50, button color should be blue200

## Chips
- [ ] Light theme color should also be updated
- [ ] For dark theme, I suggest have accented to be like primary but using lightBlue500
- [ ] Chips' delete icon has the wrong color. The design specifies that it should be blue100 inactive, and white50 on hover

## List Item Tag
- [ ] due to the way `letter-spacing` works, there is a 1px extra padding on the right. So Instead of doing `padding: 0 4px`, it should be `0 3px 0 4px`, and perhaps get flipped when written RTL... I don't know.

## Progress Bar
- [ ] I just added a suggested style for the dark theme progress bar... I forgot about this one. cc @joebochill 

## Slider
- [ ] Neither light theme nor dark theme is following the suggested colors. I am talking about the blue track and the tick marks,

## Slide Toggle
- [ ] I am more inclined to have the basic / default variant white instead of blue in the dark theme
- [ ] The "off" position color is wrong. The knob should be whiter, and the track darker.

## Toolbars
- [ ] The "warn" variant should probably be white on red500? I don't know. I never see a "warn" toolbar before. Ask Joe.

## Checkbox
- [ ] For the disabled checkbox, both the text box and the label text should use disabled text style
  - [ ] The color is black500 30% on light
  - [ ] And black300 36% on dark

## Input fields
Aside from what's mentioned in the time picker section and #123,

### primary
- [ ] the hint text is still using different colors
- [ ] outlined form field, the user input text should be centered in the text field
- [ ] The inactive filled text field is wrong
- [ ] If possible, on hover should not make the border 2px. See design file.

### warn
- [ ] red500 borders.

### Disabled
Dark theme
- [ ] hint color appears different between the legacy field and other ones. They should all be using disabled color. 
- [ ] Icon color should be the disabled color too.
- [ ] Filled variant: background color should be black800 50%.

## Info List Item
- [ ]  In dark theme, Subtitle & Info & Icon should use the secondary text color, black200. We didn't do that in the light theme because gray500 is not accessible. 
   - [ ] this might change the icon colors in drawer. For now, the drawer icons (and user menu icons) should stay to the primary text color (black50)

## Stepper
- [ ] Font size changes when an item is selected
- [ ] the circle's colors are wrong, light and dark
- [ ] Text label's colors are wrong too
- [ ] Note the font-weight changes in a visited item v. unvisited item

**Comment by emclaug2** [comment]
Thanks @huayunh for the in-depth comments!  Any light-themed notes I'm going to migrate over into a separate issue & make a JIRA for since these theme changes take some time to do.

**Comment by emclaug2** [comment]
>  the light theme tabs are using dark chevrons and

Is there more here?

**Comment by huayunh** [comment]
Oops, fixed

**Comment by emclaug2** [comment]
> In dark theme, Subtitle & Info & Icon should use the secondary text color, black200. We didn't do that in the light theme because gray500 is not accessible.

Just to clarify, do you want the PXB Drawer Nav Item subtitles to also be secondary color in dark theme too?

**Comment by emclaug2** [comment]
Changes done so far (only dark theme)

- InfoListItem subtitle & info lines are secondary in dark mode.
- Checkbox label and border uses black[300]@36%.
- Basic slide toggle uses lighter colors now (circle = primary text, bar = secondary text).
- Made issue for ListItemTag's padding in component library.
- Warn toolbar text color is white[50].
- Mobile stepper inactive dots are black[300]@36%.

Fun facts: 
- If you don't specify a variant for `mat-slide-toggle`, it's defaulted to the `accent` color.  


Updated changes found here: https://pxb-angular-theme-demo.web.app/

**Comment by huayunh** [comment]
Correct, drawer subtitle should use secondary text

**Comment by huayunh** [comment]
You may use the checkboxes in my PR comments to indicate your progress so that nothing get skipped by accident :P

**Comment by emclaug2** [comment]
> You may use the checkboxes in my PR comments to indicate your progress so that nothing get skipped by accident :P


What a cool feature, I didn't know you could do this in github.

**Comment by emclaug2** [comment]
Steppers updated now & deployed.

**Comment by emclaug2** [comment]
>  the calendar icon should be 24x24

Right now I can't change icon size without having a disproportionately small ripple effect.  Can't identify where to make the ripple bigger.

**Comment by emclaug2** [comment]
> outlined form field, the user input text should be centered in the text field

This has been brought up in the past; only reason why it's not fixed is because it's difficult.  Making a separate issue for this.

**Comment by emclaug2** [comment]
Inputs 

> warn red500 borders.

On focus?  On hover?  Always?  

Right now it's red[200] not-focused, red[500] focused.   Deploy incoming....

**Comment by emclaug2** [comment]
>  If possible, on hover should not make the border 2px. See design file.

Joe has some questions on this in his PR so I'm going to wait to see what the outcome is.

**Comment by emclaug2** [comment]
> Set the app bar to primary variant

I can't do this :(

DropdownToolbar component has no way for us to change the toolbar variant.

**Comment by emclaug2** [comment]
The input field changes should be a in better spot now; just deployed changes here: https://pxb-angular-theme-demo.web.app/

**Comment by huayunh** [comment]
> Right now I can't change icon size without having a disproportionately small ripple onclick. Can't identify where to make the ripple bigger.

For the date picker, the calendar icon is inappropriately placed to begin with. I suggest that perhaps we should just take the ripple out. When the calendar is active, you can change the calendar icon to blue200 to indicate the state change.

**Comment by huayunh** [comment]
I updated the mega checklist above to add more comments. I noticed that there are a few things you checked but are still not fully fixed yet... we can revisit them together if you want to schedule for some extra conversations outside the office hour.

**Comment by emclaug2** [comment]
> I updated the mega checklist above to add more comments. I noticed that there are a few things you checked but are still not fully fixed yet... we can revisit them together if you want to schedule for some extra conversations outside the office hour.

Whatever was marked as fixed could you just uncheck it + maybe add a note or something?   Anything that addresses a light theme change is not going to be fixed in this PR, any light-theme checkmarks will be moved to a separate issue.

**Comment by emclaug2** [comment]
Latest changes are pushed out here:  https://pxb-angular-theme-demo.web.app
This should include the button styles.

**Comment by huayunh** [comment]
Crispy! 

May want hover styles for the buttons. 

I will do a thorough review on Monday. Meanwhile, if an issue in the checkbox has been fixed or transferred, can you please either check it or delete it?

**Comment by emclaug2** [comment]
Latest changes here: https://pxb-angular-theme-demo.web.app

Hover state for icon buttons / FAB does not exist.  Any specific colors to use here @huayunh ?

**Comment by huayunh** [comment]
Do what Joe did / follow the hover design for regular buttons?

**Comment by huayunh** [comment]
Joe’s PR is almost over so I think his stuff would be a good reference point right now

**Comment by huayunh** [comment]
image

in light theme, the outline stroke width... looks like you got the legacy one correct, but the others are still 2px

**Comment by emclaug2** [comment]
> image
> 
> in light theme, the outline stroke width... looks like you got the legacy one correct, but the others are still 2px

This'll be need fixed in the light theme story; none of the tweaks in this PR should have affected light theme.

**Comment by emclaug2** [comment]
New button themes are deployed now; they should match React.

**Comment by huayunh** [comment]
## Buttons Only
image

- [ ] 1. Primary button bg color blue500, not lightBlue500
- [ ] 2. Warn button bg color red500, text color white50
- [ ] 3. Accented FAB button, match the style as described in # 1 above
- [ ] 4. outline should be red200
- [ ] 5. Wrong border color
- [ ] 6. Disabled button should not have a hovered state
- [ ] 7. Wrong hover color
- [ ] 8. Wrong hover color, should be the same style as a raised button
- [ ] 9. Wrong hover color, should be red200 20%
- [ ] (not labeled in the pic above) raised button on hover should change its elevation

Refer to Figma design file for details

**Comment by emclaug2** [comment]
@huayunh Latest button styles are deployed now; 

>  (not labeled in the pic above) raised button on hover should change its elevation

This issue is causing me some issues so I'm going to skip it for now and add an issue to adjust the shadows.

**Comment by emclaug2** [comment]
Button style, use all black:

box-shadow: 0px 2px 4px -1px rgba(66, 78, 84, 0.2), 0px 4px 5px rgba(66, 78, 84, 0.14), 0px 1px 10px rgba(66, 78, 84, 0.12);

**Comment by huayunh** [comment]
Can you verify that #125 is now fixed?

**Comment by huayunh** [comment]
## Progress Bar
image
The track should be 

## Button Toggle Group
hover background color should be blue200, 36%

## Chips
There is a little opacity thing being set on the remove icon for both default state and hover state, making the colors not applied correctly... 

present:
image

should be:
image

Same problem for their hovered state.

What you have for the disabled ones looks good to me

**Comment by huayunh** [comment]
Everything else is great! 👍

**Comment by jeffvg** [comment]
just catching up here...Is there additional work in this PR or will there be some new PR's for dark themes? I see some verifications or changes not done yet and wondering where we are with all this?

Dark theme:
Blue 200, Lt Blue 200, Red 200 should be the core colors?

**Comment by emclaug2** [comment]
> just catching up here...Is there additional work in this PR or will there be some new PR's for dark themes? I see some verifications or changes not done yet and wondering where we are with all this?
> 
> Dark theme:
> Blue 200, Lt Blue 200, Red 200 should be the core colors?

@huayunh 's been closely comparing this PR against what's in Figma & React dark themes, it's pretty close to completion.  The code itself will need refactored to make it easier to maintain, but I want to do that in a separate PR.

**Comment by emclaug2** [comment]
@huayunh The last tweaks are pushed out now: https://pxb-angular-theme-demo.web.app

**Review by huayunh — APPROVED** [review]
Only thing I noticed is the stepper circle font size, they should be 12px and centered in the circle; for the active item, they should be 12px and semibold.

Everything looks good! Thanks for the work.

**Comment by emclaug2** [comment]
> Only thing I noticed is the stepper circle font size, they should be 12px and centered in the circle; for the active item, they should be 12px and semibold.
> 
> Everything looks good! Thanks for the work.

Thanks for the reviews!  Since this affects light theme, I'll fix it there.

**Pull request merged**
